//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Borrowed()
        {
            this.BorrowedDetails = new HashSet<BorrowedDetail>();
        }
    
        public int ID { get; set; }
        public int MemberID { get; set; }
        public int StaffID { get; set; }
        public float TotalPrice { get; set; }
        public System.DateTime BorrowedTime { get; set; }
        public System.DateTime ReturnDeadline { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public bool Return { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual StaffAccount StaffAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowedDetail> BorrowedDetails { get; set; }
    }
}
