//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowed
    {
        public int id { get; set; }
        public int member_id { get; set; }
        public int book_id { get; set; }
        public int staff_id { get; set; }
        public System.DateTime borrowed_time { get; set; }
        public System.DateTime return_deadline { get; set; }
        public bool @return { get; set; }
        public System.DateTime return_time { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Member Member { get; set; }
        public virtual StaffAccount StaffAccount { get; set; }
    }
}
